version: '3'

services:
  neo-db:
    image: neo4j:4.4-community
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/Neo4j
    volumes:
      - ./database/data:/data
      - ./database/logs:/logs
    command: ["neo4j"]

  rest-api:
    build: ./backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app/
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=neo4j://neo-db:7687
      - USER_NAME=neo4j
      - PASSWORD=Neo4j
    depends_on:
      - neo-db

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - rest-api
